SELECT O.ID
    FROM ORDERS O
    WHERE O.PRODUCT_ID = 0 OR
          (O.PRODUCT_ID BETWEEN 10 AND 20 AND O.PRODUCT_ID NOT IN (12, 13, 14) AND O.PRODUCT_ID <> 15) OR
          O.PRODUCT_ID > 100 AND O.PRODUCT_ID <= 105